import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { Box, Typography } from '@mui/material'
import ThemeProvider from '@/app/provider/ThemeProvider'
import TemplateWithNavbar from '@/app/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <TemplateWithNavbar>{children}</TemplateWithNavbar>
        </ThemeProvider>
      </body>
    </html>
  )
}
