import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { Box, Typography } from '@mui/material'
import ThemeProvider from 'provider/ThemeProvider'
import SwrProvider from 'provider/SwrProvider'
import TemplateWithNavbar from 'components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'next-practice',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <SwrProvider>
            {children}
            {/* <TemplateWithNavbar>{children}</TemplateWithNavbar> */}
          </SwrProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
